name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Run build, tests, and vetting
        run: make check